version: "3.8"

services:
  app:
    image: golang:alpine
    #restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/server
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file:
      - .env

